name: Deploy website on main push

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
      - uses: actions/checkout@v4

      - name: Install Node.js 20 and dependencies
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Build project
        run: npm ci && npm run build

      - name: List built files (optional)
        run: find dist/ -print  # Use for debugging or verification

      - name: Deploy to FTP server
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: './dist/'
